// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Loremaster.Domain.Enums;
using Loremaster.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Loremaster.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260209000001_UpdateEmbeddingDimensions")]
    partial class UpdateEmbeddingDimensions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "campaign_role", new[] { "player", "master" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "ownership_type", new[] { "master", "player", "shared" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "user_role", new[] { "player", "master", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "visibility_level", new[] { "draft", "private", "campaign", "public" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: This is a partial migration that only changes the embedding column dimension
            // The full model is defined in ApplicationDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
