// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Loremaster.Domain.Enums;
using Loremaster.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Loremaster.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "campaign_role", new[] { "player", "master" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "ownership_type", new[] { "master", "player", "shared" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "user_role", new[] { "player", "master", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "visibility_level", new[] { "draft", "private", "campaign", "public" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Loremaster.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("join_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<JsonDocument>("Settings")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_campaign_deleted_at")
                        .HasFilter("deleted_at IS NOT NULL");

                    b.HasIndex("GameSystemId")
                        .HasDatabaseName("ix_campaign_game_system_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_campaign_is_active")
                        .HasFilter("deleted_at IS NULL AND is_active = true");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_join_code")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_campaign_owner_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Settings")
                        .HasDatabaseName("ix_campaign_settings")
                        .HasFilter("settings IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Settings"), "gin");

                    b.ToTable("campaign", (string)null);
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.CampaignMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<CampaignRole>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("campaign_role")
                        .HasDefaultValue(CampaignRole.Player)
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_member_campaign_id");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_campaign_member_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_campaign_member_user_id");

                    b.HasIndex("CampaignId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_campaign_member");

                    b.ToTable("campaign_member", (string)null);
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<int?>("EmbeddingDimensions")
                        .HasColumnType("integer")
                        .HasColumnName("embedding_dimensions");

                    b.Property<Guid?>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ParentDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_document_id");

                    b.Property<string>("Source")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_documents_created_at");

                    b.HasIndex("GameSystemId")
                        .HasDatabaseName("ix_documents_game_system_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_documents_owner_id");

                    b.HasIndex("ParentDocumentId")
                        .HasDatabaseName("ix_documents_parent_document_id");

                    b.HasIndex("SourceType")
                        .HasDatabaseName("ix_documents_source_type");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.EntityTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("EntityTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type_name");

                    b.Property<string>("FieldDefinitionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("field_definitions");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<string>("IconHint")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon_hint");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text")
                        .HasColumnName("review_notes");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId")
                        .HasDatabaseName("ix_entity_template_game_system_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_entity_template_owner_id");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_entity_template_status");

                    b.HasIndex("GameSystemId", "OwnerId", "EntityTypeName")
                        .IsUnique()
                        .HasDatabaseName("ix_entity_template_confirmed")
                        .HasFilter("status = 'Confirmed'");

                    b.ToTable("entity_template", (string)null);
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.GameSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("publisher");

                    b.Property<List<string>>("SupportedEntityTypes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)[]")
                        .HasColumnName("supported_entity_types")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_game_system_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_game_system_is_active")
                        .HasFilter("is_active = true");

                    b.ToTable("game_system", (string)null);
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.GenerationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid?>("CampaignMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<JsonDocument>("InputParameters")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_parameters");

                    b.Property<string>("InputPrompt")
                        .HasColumnType("text")
                        .HasColumnName("input_prompt");

                    b.Property<DateTime?>("ProcessingCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_completed_at");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("request_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_entity_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_generation_request_campaign_id")
                        .HasFilter("campaign_id IS NOT NULL");

                    b.HasIndex("CampaignMemberId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_generation_request_created_at");

                    b.HasIndex("InputParameters")
                        .HasDatabaseName("ix_generation_request_input_parameters")
                        .HasFilter("input_parameters IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("InputParameters"), "gin");

                    b.HasIndex("RequestType")
                        .HasDatabaseName("ix_generation_request_request_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_generation_request_status");

                    b.HasIndex("TargetEntityType")
                        .HasDatabaseName("ix_generation_request_target_entity_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_generation_request_user_id");

                    b.ToTable("generation_request", (string)null);
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.GenerationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GenerationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_request_id");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<JsonDocument>("ModelParameters")
                        .HasColumnType("jsonb")
                        .HasColumnName("model_parameters");

                    b.Property<JsonDocument>("RawOutput")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_output");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result_type");

                    b.Property<int>("SequenceOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("sequence_order");

                    b.Property<JsonDocument>("StructuredOutput")
                        .HasColumnType("jsonb")
                        .HasColumnName("structured_output");

                    b.Property<JsonDocument>("TokenUsage")
                        .HasColumnType("jsonb")
                        .HasColumnName("token_usage");

                    b.HasKey("Id");

                    b.HasIndex("GenerationRequestId")
                        .HasDatabaseName("ix_generation_result_request");

                    b.HasIndex("ModelName")
                        .HasDatabaseName("ix_generation_result_model")
                        .HasFilter("model_name IS NOT NULL");

                    b.HasIndex("ResultType")
                        .HasDatabaseName("ix_generation_result_type");

                    b.ToTable("generation_result", null, t =>
                        {
                            t.HasCheckConstraint("chk_confidence_score", "confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)");
                        });
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.GenerationResultSource", b =>
                {
                    b.Property<Guid>("GenerationResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_result_id");

                    b.Property<Guid>("RagSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("rag_source_id");

                    b.Property<string>("Excerpt")
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<decimal?>("RelevanceScore")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("relevance_score");

                    b.HasKey("GenerationResultId", "RagSourceId");

                    b.HasIndex("RagSourceId")
                        .HasDatabaseName("ix_generation_result_source_rag");

                    b.ToTable("generation_result_source", null, t =>
                        {
                            t.HasCheckConstraint("chk_relevance_score", "relevance_score IS NULL OR (relevance_score >= 0 AND relevance_score <= 1)");
                        });
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.LoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<JsonDocument>("Attributes")
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("GenerationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_request_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_template");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<OwnershipType>("OwnershipType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ownership_type")
                        .HasDefaultValue(OwnershipType.Master)
                        .HasColumnName("ownership_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<VisibilityLevel>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("visibility_level")
                        .HasDefaultValue(VisibilityLevel.Campaign)
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_lore_entity_deleted_at")
                        .HasFilter("deleted_at IS NOT NULL");

                    b.HasIndex("GenerationRequestId")
                        .HasDatabaseName("ix_lore_entity_generation")
                        .HasFilter("generation_request_id IS NOT NULL AND deleted_at IS NULL");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_lore_entity_owner_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("CampaignId", "EntityType")
                        .HasDatabaseName("ix_lore_entity_templates")
                        .HasFilter("is_template = true AND deleted_at IS NULL");

                    b.HasIndex("CampaignId", "OwnerId")
                        .HasDatabaseName("ix_lore_entity_player_characters")
                        .HasFilter("entity_type = 'character' AND ownership_type = 'Player' AND deleted_at IS NULL");

                    b.HasIndex("CampaignId", "Visibility")
                        .HasDatabaseName("ix_lore_entity_campaign_visibility")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("lore_entity", (string)null);
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.LoreEntityImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text")
                        .HasColumnName("error_details");

                    b.Property<JsonDocument>("ExtractionResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("extraction_result");

                    b.Property<JsonDocument>("FieldMapping")
                        .HasColumnType("jsonb")
                        .HasColumnName("field_mapping");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<string>("ImportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("import_type");

                    b.Property<Guid>("LoreEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("lore_entity_id");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("processing_status");

                    b.Property<string>("SourceFileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_file_url");

                    b.Property<string>("SourceFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_filename");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionResult")
                        .HasDatabaseName("ix_lore_entity_import_extraction_result")
                        .HasFilter("extraction_result IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ExtractionResult"), "gin");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("ix_lore_entity_import_file_hash")
                        .HasFilter("file_hash IS NOT NULL");

                    b.HasIndex("ImportType")
                        .HasDatabaseName("ix_lore_entity_import_type");

                    b.HasIndex("LoreEntityId")
                        .HasDatabaseName("ix_lore_entity_import_entity_id");

                    b.HasIndex("ProcessingStatus")
                        .HasDatabaseName("ix_lore_entity_import_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_lore_entity_import_user_id");

                    b.ToTable("lore_entity_import", (string)null);
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.LoreEntityRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relationship_type");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_entity_id");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_entity_id");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipType")
                        .HasDatabaseName("ix_lore_entity_relationship_type");

                    b.HasIndex("SourceEntityId")
                        .HasDatabaseName("ix_lore_entity_relationship_source");

                    b.HasIndex("TargetEntityId")
                        .HasDatabaseName("ix_lore_entity_relationship_target");

                    b.HasIndex("SourceEntityId", "TargetEntityId", "RelationshipType")
                        .IsUnique()
                        .HasDatabaseName("uq_lore_entity_relationship");

                    b.ToTable("lore_entity_relationship", null, t =>
                        {
                            t.HasCheckConstraint("chk_no_self_relationship", "source_entity_id != target_entity_id");
                        });
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_projects_owner_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_projects_status");

                    b.HasIndex("OwnerId", "Status")
                        .HasDatabaseName("ix_projects_owner_status");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.RagSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_rag_source_content_hash")
                        .HasFilter("content_hash IS NOT NULL");

                    b.HasIndex("GameSystemId")
                        .HasDatabaseName("ix_rag_source_game_system_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_rag_source_is_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("SourceType")
                        .HasDatabaseName("ix_rag_source_source_type");

                    b.ToTable("rag_source", (string)null);
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("InvitationCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("invitation_code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<Guid?>("MasterId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<UserRole>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("user_role")
                        .HasDefaultValue(UserRole.Player)
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_user_deleted_at")
                        .HasFilter("deleted_at IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_external_id")
                        .HasFilter("external_id IS NOT NULL AND deleted_at IS NULL");

                    b.HasIndex("InvitationCode")
                        .IsUnique()
                        .HasDatabaseName("ix_user_invitation_code")
                        .HasFilter("invitation_code IS NOT NULL AND deleted_at IS NULL AND is_active = true");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_user_is_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("MasterId")
                        .HasDatabaseName("ix_user_master_id")
                        .HasFilter("master_id IS NOT NULL AND deleted_at IS NULL");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_user_role")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("Campaigns")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Loremaster.Domain.Entities.User", "Owner")
                        .WithMany("OwnedCampaigns")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSystem");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.CampaignMember", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Members")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loremaster.Domain.Entities.User", "User")
                        .WithMany("CampaignMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.Document", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany()
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Loremaster.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSystem");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.EntityTemplate", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany()
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loremaster.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loremaster.Domain.Entities.Document", "SourceDocument")
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GameSystem");

                    b.Navigation("Owner");

                    b.Navigation("SourceDocument");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.GenerationRequest", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.Campaign", "Campaign")
                        .WithMany("GenerationRequests")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Loremaster.Domain.Entities.CampaignMember", null)
                        .WithMany("GenerationRequests")
                        .HasForeignKey("CampaignMemberId");

                    b.HasOne("Loremaster.Domain.Entities.User", "User")
                        .WithMany("GenerationRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.GenerationResult", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.GenerationRequest", "GenerationRequest")
                        .WithMany("Results")
                        .HasForeignKey("GenerationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenerationRequest");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.GenerationResultSource", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.GenerationResult", "GenerationResult")
                        .WithMany("Sources")
                        .HasForeignKey("GenerationResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loremaster.Domain.Entities.RagSource", "RagSource")
                        .WithMany("UsedInResults")
                        .HasForeignKey("RagSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenerationResult");

                    b.Navigation("RagSource");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.LoreEntity", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.Campaign", "Campaign")
                        .WithMany("LoreEntities")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loremaster.Domain.Entities.GenerationRequest", "GenerationRequest")
                        .WithMany("GeneratedEntities")
                        .HasForeignKey("GenerationRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Loremaster.Domain.Entities.User", "Owner")
                        .WithMany("OwnedLoreEntities")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("GenerationRequest");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.LoreEntityImport", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.LoreEntity", "LoreEntity")
                        .WithMany("Imports")
                        .HasForeignKey("LoreEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loremaster.Domain.Entities.User", "User")
                        .WithMany("Imports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoreEntity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.LoreEntityRelationship", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.LoreEntity", "SourceEntity")
                        .WithMany("OutgoingRelationships")
                        .HasForeignKey("SourceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loremaster.Domain.Entities.LoreEntity", "TargetEntity")
                        .WithMany("IncomingRelationships")
                        .HasForeignKey("TargetEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceEntity");

                    b.Navigation("TargetEntity");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.Project", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.RagSource", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("RagSources")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.User", b =>
                {
                    b.HasOne("Loremaster.Domain.Entities.User", "Master")
                        .WithMany("Players")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_master");

                    b.Navigation("Master");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("GenerationRequests");

                    b.Navigation("LoreEntities");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.CampaignMember", b =>
                {
                    b.Navigation("GenerationRequests");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.GameSystem", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("RagSources");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.GenerationRequest", b =>
                {
                    b.Navigation("GeneratedEntities");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.GenerationResult", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.LoreEntity", b =>
                {
                    b.Navigation("Imports");

                    b.Navigation("IncomingRelationships");

                    b.Navigation("OutgoingRelationships");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.RagSource", b =>
                {
                    b.Navigation("UsedInResults");
                });

            modelBuilder.Entity("Loremaster.Domain.Entities.User", b =>
                {
                    b.Navigation("CampaignMemberships");

                    b.Navigation("GenerationRequests");

                    b.Navigation("Imports");

                    b.Navigation("OwnedCampaigns");

                    b.Navigation("OwnedLoreEntities");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
